### ISSUE TITLE
Setup back button for Android

### ISSUE THREAD

**Issue by vidbina** [Suprnovae/abc-totaal-notitieblok#11]
As a user, pressing the back button should return me to the previous view in the navigation stack.

Currently back equates to exit

**Comment by vidbina** [comment]
Hey @zirconias, have you already started on this?
If you have let me see what you have been working on, otherwise I have a merged some stuff I had stashed a while back in the branch setup/backbutton c0a8655

**Comment by zirconias** [comment]
hi @vidbina  not yet,  i'll work on it later in the day if you don't mind,  
i have a roadmap ,  i think we gonna play with the navigator popup and back things...

**Comment by vidbina** [comment]
Don't worry about this. Tackle #12 instead. I already merged the `BackAndroid` code in c0a8655. BTW if you start working on the camera button, start from `dev` :wink:

**Comment by zirconias** [comment]
it handle only hardware button ! what about the navigation bar if there is any ?
