### ISSUE TITLE
Setup basic iOS UI

### ISSUE THREAD

**Issue by vidbina** [Suprnovae/abc-totaal-notitieblok#4]
Setup a navigation bar with the "Add new record" button and a dummy list view

**Comment by vidbina** [comment]
It's all in master now, I still have to decide on `NavigatorIOS` vs `Navigator` 💭

**Comment by vidbina** [comment]
- [x] setup multiple scenes for navigator to test navigator behavior
- [x] determine design of navigation bar
- [x] style the navigation bar

**Comment by vidbina** [comment]
@AlinaChernenko can you please style the navigation bars.
Nothing really changes except the colors. I want the background of the Toolbar in the Android view to be blue  #2196F3 while the text is white #FFF and in the iOS view NavigatorIOS has the background #2196F3 and the text and icons being coloured #FFF.

Please commit the changes for Android separately and the changes for iOS seperately? It may be in the same branch but it they are separate it makes cherry-picking and merging easier for me :wink:

**Comment by AlinaChernenko** [comment]
Hi @vidbina , committed 2 different small updates to new ui/topbar-blue branch. Let me know if I need to create a PR. Thanks!
